[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
commands = [
    "chmod +x ./mvnw",
    "./mvnw -B clean package -DskipTests"
]

[phases.start]
command = "java -jar target/email-writer-0.0.1-SNAPSHOT.jar"